name: 'Ecotone Framework'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  # 1. for Github split
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  get_packages:
    name: Package splitting
    runs-on: ubuntu-latest

    steps:
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - uses: actions/checkout@v2

      - name: Get Packages
        id: get_json
        run: echo "::set-output name=json::$(bin/get-packages)"

      - name: Output Packages
        run: echo "${{ steps.get_json.outputs.json }}"

    outputs:
      matrix: ${{ steps.get_json.outputs.json }}

  split_packages:
    name: Split Package ${{ matrix.package.name }}
    needs: get_packages
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.get_packages.outputs.matrix) }}

    steps:
      -   uses: actions/checkout@v2

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          # ↓ split "packages/easy-coding-standard" directory
          package_directory: '${{ matrix.package.directory }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: 'ecotoneframework'
          repository_name: '${{ matrix.package.name }}'

          # ↓ the user signed under the split commit
          user_name: "Dariusz Gafka"
          user_email: "dgafka.mail@gmail.com"

      # with tag
#      -
#        if: "startsWith(github.ref, 'refs/tags/')"
#        uses: "symplify/monorepo-split-github-action@2.1"
#        with:
#          tag: ${GITHUB_REF#refs/tags/}
#
#          # ↓ split "packages/easy-coding-standard" directory
#          package_directory: 'packages/${{ matrix.package.directory }}'
#
#          # ↓ into https://github.com/symplify/easy-coding-standard repository
#          repository_organization: 'ecotoneframework'
#          repository_name: '${{ matrix.package.name }}'
#
#          # ↓ the user signed under the split commit
#          user_name: "Dariusz Gafka"
#          user_email: "dgafka.mail@gmail.com"